baseURL = 'https://cranky-wilson-4208f4.netlify.app'
languageCode = 'en-us'
title = 'My site'
theme="hugo-PaperMod-master"
authors="Lucas"
[menu]
[[menu.main]]
    identifier='introduction'
    name='Introduction'
    title='Introduction section'
    url="introduction"
    weight=10
[[menu.main]]
    identifier='activities'
    name='Profeional activities'
    title='activities'
    url="activities"
    weight=10
